#!/bin/sh

apt-get update
chmod +x p4d
mv p4d /usr/local/bin
chmod +x p4
mv p4 /usr/local/bin
adduser perforce --gecos "Perforce,User,0,0,0" --disabled-password
mkdir /perforce_depot
chown perforce /perforce_depot
mkdir /var/log/perforce
chown perforce /var/log/perforce
apt-get install daemon
mv p4dservice /etc/init.d
chmod +x /etc/init.d/p4dservice
ln -s /etc/init.d/p4dservice p4dservice
chmod +x p4dservice
cd /etc/init.d
update-rc.d p4dservice defaults